# Generated by Django 4.2 on 2023-04-09 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='iscompleted',
        ),
        migrations.CreateModel(
            name='todoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
                ('iscompleted', models.BooleanField()),
                ('status', models.CharField(choices=[('to-do', 'to-do'), ('in-progress', 'in-progress'), ('done', 'done')], max_length=12)),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.todo')),
            ],
        ),
    ]
