# Generated by Django 4.2 on 2023-04-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('isCompleted', models.BooleanField(default=False)),
                ('todo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.todo')),
            ],
        ),
    ]
